### PR TITLE
Chore: ListItem supports titleElement

### PR DESCRIPTION
**Pull request by ttkien**
simulator_screenshot_F9119328-D3C6-4D05-9774-74A2D849034B

### CODE REVIEW

**Review by huyvohcmc — APPROVED** [review]
LGTM!

**Comment by toan2406** [comment]
Should we support subtitle too? So that everyone can just use later

**Comment by ttkien** [comment]
Okie. Let me add

**Comment by ttkien** [comment]
@toan2406 added, Please help me review again

**Review by toan2406 — APPROVED** [review]

**Review by MinhDinh123 — APPROVED** [review]

**Review by quynhethereal — APPROVED** [review]

**Pull request merged**
